### PR TITLE
Add nick command (Fixes #18)

### LINKED ISSUE #18: Nickname
Can you add /nick ?

### PR DESCRIPTION
**Pull request by funniray**
Adds a nickname command and lets users use nicknames in commands. Translations are only in English. Fixes #18

### CODE REVIEW

**Comment by yescallop** [comment]
Sorry for belated reply. Your changes appear to depend on another plugin. I don't know what that plugin is used for, however, is it really necessary to do that? In my opinion, plugin depending will result in a poor user experience.

**Comment by funniray** [comment]
I’m not sure if it’s 100% dependent on LuckPerms, but LuckPerms is by far the best permission plugin for Nukkit. I could probably add a config option to enable/disable Essentials pulling the player’s prefix/suffix from LuckPerms.

**Comment by funniray** [comment]
Yeah, I just double checked and I believe that it only softdepends on LuckPerms to get prefix/suffix data. I can add a config option to disable this, but if I remember correctly, there’s no main config in Essentials for Nukkit, right?

**Comment by funniray** [comment]
There, I removed LuckPerms as a dependency. They can now just use LPChat for getting the prefix/suffix.

**Comment by yescallop** [comment]
I'm sorry but this repository is not maintained anymore.

**Pull request closed without merging**
