### PR TITLE
Add new commands

### PR DESCRIPTION
**Pull request by Creeperface01**
but i didn't test it

### CODE REVIEW

**Comment by Creeperface01** [comment]
srsly?? -,- i updated my fork -,-

**Comment by yescallop** [comment]
you didn't:( use fetch and rebase instead

**Comment by yescallop** [comment]
git remote add yescallop https://github.com/yescallop/EssentialsNK.git
git fetch yescallop
git rebase yescallop/master
git push --force

**Comment by yescallop** [comment]
or I redo it and you clear your fork?

**Comment by yescallop** [comment]
i added speed command, no time for adding god command and PlayerData, you can clear your fork and retry to open pull request

**Pull request closed without merging**
